--Q1. What is the total revenue generated by Male vs Female customers?

--Q2. Which customer used a discount but still spent more than average purchase?

--Q3. Which are the top 5 products with highest average review rating?

--Q4. Compare the average purchase amount between Standard and Express shipping.

--Q5. Do subscribers spend more? comoare average spend and total revenue between subscribers and non-subscribers

--Q6. Which 5 products have the highest percentage of purchase with discount applied

--Q7. What are top 3 most purchased product within each category?

--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

--Q9. What is the revenue contribution of each age group?

