--Q1. What is the total revenue generated by Male vs Female customers?
select gender, SUM(purchase_amount) as total_revenue
from customer
group by gender

--Q2. Which customer used a discount but still spent more than average purchase?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with highest average review rating?
select item_purchased, ROUND(AVG(review_rating),2) as average_review_rating
from customer
group by item_purchased
order by AVG(review_rating)
limit 5

--Q4. Compare the average purchase amount between Standard and Express shipping.
select shipping_type, ROUND(AVG(purchase_amount),2) as average_purchase_amount
from customer
WHERE shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribers spend more? comoare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
  COUNT(customer_id) as total_customers
  ROUND(AVG(purchase_amount),2) as average_spend,
  ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
ORDER BY total_revenue, average_spend desc

--Q6. Which 5 products have the highest percentage of purchase with discount applied
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

--Q7. What are top 3 most purchased product within each category?
select category, item_purchased,
       COUNT(customer_id) as total_purchases,
       RANK() OVER (PARTITION BY CATEGORY ORDER BY COUNT(customer_id) desc) as rnk
  from customers
  where dns_rnk <= 3

--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, COUNT(customer_id) as repeat_buyers
from customer
where previous_purchase > 5
group by subscription_status

--Q9. What is the revenue contribution of each age group?
select age_group, SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

